= FASTA

FASTA is a text-based format for representing either nucleotide sequences or peptide sequences, in which nucleotides or amino acids are represented using single-letter codes.

Some simple example of one sequence in FASTA format:

.A FASTA nucleotide sequence
----
>chr1 <1>
GTCCTCGTGGCCACCCCAGGCTGCTGCACGCAGAGCAGTTCGGCTGTCTGCATCTGCACAGTCTACCTTTACGCCAGCGT <2>
----

.A FASTA peptide sequence
----
>gi|31563518|ref|NP_852610.1| microtubule-associated proteins 1A/1B light chain 3A isoform b [Homo sapiens] <1>
MKMRFFSSPCGKAAVDPADRCKEVQQIRDQHPSKIPVIIERYKGEKQLPVLDKTKFLVPDHVNMSELVKIIRRRLQLNPTQAFFLLVNQHSMVSVSTPIADIYEQEKDEDGFLYMVYASQETFGFI <2>
----
<1> sequence description, can be a long description (see below)
<2> raw sequence

The word following the ">" symbol is the identifier of the sequence, and the rest of the line is the description (both are optional). There should be no space between the ">" and the first letter of the identifier. It is recommended that all lines of text be shorter than 80 characters. The sequence ends if another line starting with a ">" appears; this indicates the start of another sequence.





