= GRAPE
:user: ngs00
:grape-github: https://github.com/guigolab/grape-nf

This section of the workshop is a step by step tutorial on how to run the Grape pipeline on the workshop sample data.

== Get the pipeline

The pipeline codebase is on {grape-github}[Github^]. The Grape repository is configured to fullfil Nextflow requirements for pipeline sharing. In order to get the latest version of the pipeline run the following command:

[source,cmd]
----
nextflow pull guigolab/grape-nf
----

----
Checking guigolab/grape-nf ...
 downloaded from https://github.com/guigolab/grape-nf.git
----

The pipeline has been cloned from the github repository and saved in:

[listing,subs="attributes"]
----
~/.nextflow/assets/guigolab/grape-nf/
----

You can see the help message of the pipeline by running:

[source,cmd]
----
nextflow run grape-nf --help
----

[listing%nowrap]
include::https://raw.githubusercontent.com/guigolab/grape-nf/master/docs/src/quickstart.adoc[lines=131..158]

NOTE: since the pipeline has beed already pulled to the local system we can omit the repository owner name (`guigolab`) when running the pipeline.

== Setup

We need to create a working directory for the pipeline run. Create a folder named `grape` in your home folder and go inside the folder:

[source,cmd]
----
mkdir grape && cd grape
----

=== Input data

include::https://raw.githubusercontent.com/guigolab/grape-nf/master/docs/src/quickstart.adoc[lines=162..173]

Here is an example:

----
mouse_cns_E14_rep1	mouse_cns_E14_rep1	mouse_cns_E14_rep1_1.fastq.gz	fastq	FqRd1
mouse_cns_E14_rep1	mouse_cns_E14_rep1	mouse_cns_E14_rep1_2.fastq.gz	fastq	FqRd2
----

You can have have a look at the index file for the workshop:

[source,cmd,subs='attributes']
----
cat /users/{user}/data/index.tsv
----

=== Pipeline configuration

Create a `nextflow.config` file in the current directory with the following content:

[source,java,subs='attributes,verbatim']
----
params { // <1>
	index = '/users/{user}/data/index.tsv'
	genome = '/users/{user}/refs/mouse_genome_mm9.fa'
	annotation = '/users/{user}/refs/mm65.long.ok.gtf'
	genomeIndex = '/users/{user}/refs/mouse_genome_mm9_STAR_index'
  steps = 'mapping,bigwig'
}

trace.enabled = true // <2>
timeline.enabled = true // <3>

process { // <4>
	executor = 'sge'
	queue    = 'NGS'
	penv = 'smp'
}

includeConfig "/users/{user}/ngs.config" // <5>
----
<1> Parameter definitions. It could also be done from the command line (e.g. `--genome /users/{user}/refs/mouse_genome_mm9.fa`).
<2> Enable process execution tracing
<3> Enable HTML timeline generation
<4> Process options for running in the workshop HPC cluster
<5> Include an external configuration file

== Run

Grape uses Nextflow profiles to define the set of tools to be used for the pipeline run. To date three main profiles are available:

[cols="l,1", options="autowidth"]
|===
| gemflux  | GEM for mapping, custom scripts for RNAseq Signal and Contig and FluxCapacitor for genes and transcripts expression quantification
| starrsem | STAR for mapping and RNAseq Signal, custom script for Contig and RSEM for gene and transcripts expression quantification
| starflux | STAR for mapping and RNAseq Signal, custom script for Contig and FluxCapacitor for gene and transcripts expression
						 quantification
|===
plus

Profiles can be specified explicitly on the command line. There is also a `standard` profile used as the default when no profile is specified. For Grape, it is the same as `starrsem` plus an additional configuration option and we are going to use this profile. It looks like:

[source,java]
----
include::https://raw.githubusercontent.com/guigolab/grape-nf/master/nextflow.config[lines=36..47]
----

The `bamSort` options tells the pipeline to use `samtools` for sorting the mapping output file.

In order to run the pipeline, use this command:

[source,cmd]
----
nextflow -bg run grape-nf > pipeline.log
----

=== Monitor the run

The status of the pipeline run can be monitored by looking at the `pipeline.log` files we specified above.

[source,cmd,subs="attributes"]
----
tail -f ~/grape/pipeline.log
----
[subs="specialchars,attributes,quotes,replacements,macros,post_replacements"]
----
...
===============
Output files db -> /nfs/users/ngs00/grape/pipeline.db
===============

[warm up] executor > sge
[65/aa3f6e] Submitted process > fastaIndex (mouse_genome_mm9-SAMtools-0.1.19)
[#46/1c2697#] Submitted process > mapping (mouse_cns_E18_rep1-STAR-2.4.0j)
[3b/7b0ffc] Submitted process > mapping (mouse_cns_E14_rep1-STAR-2.4.0j)
[0a/344ded] Submitted process > mapping (mouse_cns_E14_rep2-STAR-2.4.0j)
[5f/b56606] Submitted process > mapping (mouse_cns_E18_rep2-STAR-2.4.0j)
icon:circle-o-notch[pulse]
----

The highlighted string specifies the prefix of the process working folder. It is relative to the pipeline working folder which, by default, is `work` inside the current folder. To get the full name of the folder you need to use bash `autocompletion` feature. Type the path to the folder, include the prefix and press kbd:[TAB]. For the previous example process:

[subs="specialchars,attributes,quotes,replacements,macros,post_replacements"]
----
ls /nfs/users/ngs00/grape/work/46/1c2697kbd:[TAB]77223fec512d031da42ff956/
----

If the run finishes wihtout errors the pipeline log file ends with a success message:

----
...

-----------------------
Pipeline run completed.
-----------------------
----

== Results

The path and metadata of output files generated by the pipeline run are written inside a `TAB` separated file, named `pipeline.db`. The file can be found inside the pipeline working folder.

The first 5 columns follow the same schema as the input index file. Here is a description of the remaining columns:

[cols="1,l,1",options="autowidth"]
|===
| [red]#{counter:index-qs}# | read configuration | the configuration of the reads (e.g. `Paired-End`)
| [red]#{counter:index-qs}# | strandness         | the strandness of the experiments, automaticalliy inferred from the
																								   mapping files (e.g. `MATE2_SENSE`)
|===

Have a look at the generated db file:

[source,cmd]
----
less -S ~/grape/pipeline.db
----
